theme = "dark_plus"

[editor]
mouse = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"space" = { "space" = "file_picker" }
